spring.application.name=civicaid
server.port=8081

jwt.secreteKey=yeh87wqye8721e21heiu21e2197ey219e21h21iu219d2hd91db21d19hf91bd


spring.datasource.url=jdbc:mysql://localhost:3306/civicaidb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect